name: wallpapers
description: A Wallpapers app

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hidden_drawer_menu: ^2.0.1
  google_fonts: ^1.0.0
  wallpaper_manager: ^1.0.10
  flutter_cache_manager:
  lottie:
  cached_network_image: ^2.5.1
  shared_preferences: ^2.0.4
  gesture_zoom_box: ^0.0.3
  flutter_svg:
  flutter_staggered_grid_view:
  url_launcher:
  toast: ^0.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/lottiefiles/
    - assets/svg/
    - assets/images/