name: wallpapers
description: A Wallpapers app

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hidden_drawer_menu: ^2.0.1

flutter:
  uses-material-design: true