name: wallpapers
description: A Wallpapers app

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hidden_drawer_menu: ^2.0.1
  google_fonts: ^1.0.0
  wallpaper_manager: ^1.0.10
  flutter_cache_manager:
  lottie:

flutter:
  uses-material-design: true